### ISSUE TITLE
Create a static page for the home route using HTML, CSS and jinja2 templating

### ISSUE THREAD

**Issue by CIPHERTron** [codeisscience/journal-policy-tracker-backend#37]
As of now, the home route i.e. https://journal-policy-tracker.herokuapp.com/ has a bare HTML skeleton. It would be great if we could just beautify it using some basic HTML, CSS, and Jinja2 templating.

**Comment by oneknucklehead** [comment]
Hey! is the issue still open?

**Comment by JPTIZ** [comment]
> Hey! is the issue still open?

Well, as we don't have any PR solving it, I think you can go for it :) @CIPHERTron should we wait until any migration to TS is settled?

**Comment by oneknucklehead** [comment]
Cool! Should I wait till @CIPHERTron replies, or should I just go for it? @JPTIZ

**Comment by oneknucklehead** [comment]
@CIPHERTron @JPTIZ ?

**Comment by yochannah** [comment]
@oneknucklehead please just go for it for now :)

**Comment by Ananya2001-an** [comment]
Hi! Is this issue still open?

**Comment by JPTIZ** [comment]
> Hi! Is this issue still open?

Actually there's an ongoing migration to Express (#57 for example). But thanks  for asking and, if you wish to contribute in this project, talk to us on our Slack (https://join.slack.com/t/codeisscience/shared_invite/zt-1c3lat8wh-dIqC~IQeizavPsNKzJN2zQ) to find out a good task to work on :)
