### ISSUE TITLE
Database tables are not being created on Heroku

### ISSUE THREAD

**Issue by JPTIZ** [codeisscience/journal-policy-tracker-backend#42]
When running the project locally, tables seems to be created as expected, but on Heroku deploy it is not (raising a exception with the message "no table 'users'").

Tasklist:
- [ ] Ensure that locally, in a clean environment (no database file or other generated content), if database is being created.
  - [ ] If it is not, try to fix it locally (always ensuring a clean environment).
- [ ] Make sure (still locally) that a previous content isn't overwritten when restarting the server.
- [ ] Deploy to heroku and repeat the steps that were done locally ensuring Heroku doesn't get configured to delete the previous database file.

**Comment by erik-whiting** [comment]
hello! I reported [this issue](https://github.com/codeisscience/journal-policy-tracker-frontend/issues/62) on the `journal-policy-tracker-frontend` repository. I think the issue I reported would most likely be solved by fixing this issue, do you think that's correct?

If this is still an active project and y'all are looking for contributors, I'd be happy to take a stab at fixing this if someone isn't already on it. Let me know, thanks!

**Comment by erik-whiting** [comment]
Hey @JPTIZ, I've created a fix for this that checks off everything but the last box on your tasklist. Is there a way I can get added to the Heroku group or would you prefer a maintainer deploy my fixes?

Also, I had a couple of questions just from looking through the code. You say that tables were created as expected locally, but they were not for me. I made some changes to make the database ready to go once you run `poetry run python -m codecompl`, how had your team been building the database?

Last question, can I make a minor improvement to the journal `POST` route? Basically, it's set to return a happy message no matter what and I'd like to add error handling/messaging if it's not a big deal. If not, I'll just make a PR with what I've got.

Let me know about the Heroku part!

**Comment by erik-whiting** [comment]
Howdy @JPTIZ I made a pull request for this issue [here](https://github.com/codeisscience/journal-policy-tracker-backend/pull/46).

My PR addresses each item in your task list except for the last one. According to [Heroku's own documentation](https://devcenter.heroku.com/articles/sqlite3#disk-backed-storage), it seems like using SQLite as a database pretty much guarantees that you you'll lose your data on every deploy and at least once every 24 hours. So with the current architecture, I think the last task list item is impossible 🙁. I've documented all of this in my PR.

The project will most likely have to use a more production-ready RDBMS system like MySQL or Postgres. I'm happy to start on the work for that or at least draw up some plans for getting that done. Just let me know!

Thanks for your help so far!

**Comment by erik-whiting** [comment]
Howdy @JPTIZ ! Just wanted to see if you were able to look at my [PR](https://github.com/codeisscience/journal-policy-tracker-backend/pull/46) from last week. I know y'all are busy and it's probably a big PR so let me know if I can make it easier on you all or help out in any way.
