### ISSUE TITLE
Create a user model

### ISSUE THREAD

**Issue by ikeadeoyin** [codeisscience/journal-policy-tracker-backend#49]
Creating a user model in relation to roles and permission will help implement role-based access control for each request.
A sample user model will include attributes like id, username, email address and others.
`
User = {
  id: Integer, 
  username: String,
  firstName: String,
  lastName: String,
  emailAddress: String,
  createdAt: Datetime,
  updatedAt: Datetime
}`

**Comment by JPTIZ** [comment]
About `updateAt`, if it is to implement some kind of changelog, we should consider if making an `UserUpdates` table would be a better approach, depending on what would be its main purpose.
