### ISSUE TITLE
Provide a way of backuping the database

### ISSUE THREAD

**Issue by JPTIZ** [codeisscience/journal-policy-tracker-backend#5]
We won't want to loose the data we gathered because of some kind of server shutdown, so there probably should be a way of backuping the data outside the database.

### Current possibilities

Maybe having a `/backup` route with a limit of accesses per hour for a single host. The limit would be just to prevent excessive accesses that could lead a DoS.

**Comment by CIPHERTron** [comment]
In SQLite3, there are `.backup` and `.dump` commands.
`.backup` will make a new sq3 file whereas `.dump` will dump all the data into a text file. However, we can customize it if we want to backup specific tables.
`
sqlite3 project_db.sq3 ".backup 'backup_db.sq3'"
`

Also, can't we use Cloudfare to prevent DDoS attacks? @JPTIZ
