### ISSUE TITLE
Proposal for a Pull Request Template as well as an Issue Template

### ISSUE THREAD

**Issue by CIPHERTron** [codeisscience/journal-policy-tracker-backend#7]
While I was going to open a new issue, I noticed that there's neither Pull Request Template nor Issue Template. So, I would like to propose that we should add one. When you add a pull request template to your repository, project contributors will automatically see the template’s contents in the pull request body. The same goes with the issue template as well. 

When you have a well-defined template, it makes things highly scannable to the human eye. Also, highly parsable if desired. Communication runs best via well-defined formats. That’s why a template is more important than the same information put succinctly.

More info at:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by yochannah** [comment]
@CIPHERTron please go for it if you would like to pick this up!

**Comment by CIPHERTron** [comment]
Thanks @yochannah !
