### ISSUE TITLE
Adding the sort function to getAllJournals query.

### ISSUE THREAD

**Issue by d-e-v-esh** [codeisscience/journal-policy-tracker-backend#71]
### Current Behaviour
Currently when we add a new journal with the `createJournal` mutation and call the `getAllJournals` query, that newly created journal shows up at the back of the response array.

### Expected Behaviour
That newly created jounral is supposed to show up at the front of the response array. We need to sort the entire result of journals array before we apply `skip` and `limit` pagination.

[This](https://github.com/codeisscience/journal-policy-tracker-backend/blob/dev/src/resolvers/journalResolver.js#L20) is where the `getAllJournals` function is located.

**Comment by khanjasir90** [comment]
@d-e-v-esh can i work on this!

**Comment by d-e-v-esh** [comment]
Yes please 👍
