### ISSUE TITLE
`changeUsername` user Mutation

### ISSUE THREAD

**Issue by d-e-v-esh** [codeisscience/journal-policy-tracker-backend#73]
Currently there is no way for a registered user to change its `username`.

Create a `changeUsername` mutation which will let users change their current `username`. This mutation should look in the database to see if another user with that username already exists, if an identical username exists then respond with eith an error saying 'username already exists". If there is no identical username then run the mutation.

**Comment by HeonHeo23** [comment]
Can I take this issue?

**Comment by d-e-v-esh** [comment]
@HeonHeo23 Yes for sure! Let me know if you face any problems. 👍

**Comment by HeonHeo23** [comment]
@d-e-v-esh Can you share any resources to learn about the frameworks used in the project?

**Comment by d-e-v-esh** [comment]
I found a couple of YouTube videos that might be helpful to you:
1. [Complete GraphQL API tutorial using Apollo Express and MongoDB](https://youtu.be/xUQ-hNRHCgs)
2. [Build a GraphQL Server with Node.js and MongoDB](https://youtu.be/YFkJGEefgU8)

Other than that, you can just read the documentation for the tools that were used in the project (mongoose, GraphQL, Express, ApolloServer) etc, that'll be helpful.

**Comment by hazardemircan** [comment]
> I found a couple of YouTube videos that might be helpful to you:
> 
> 1. [Complete GraphQL API tutorial using Apollo Express and MongoDB](https://youtu.be/xUQ-hNRHCgs)
> 2. [Build a GraphQL Server with Node.js and MongoDB](https://youtu.be/YFkJGEefgU8)
> 
> Other than that, you can just read the documentation for the tools that were used in the project (mongoose, GraphQL, Express, ApolloServer) etc, that'll be helpful.

I personally like Ben Awad's videos that @d-e-v-esh mentioned on second link. You can watch from him

**Comment by hazardemircan** [comment]
@d-e-v-esh @HeonHeo23 
If issue couldn't be close, i can handle it, thanks

**Comment by HeonHeo23** [comment]
@hazardemircan
I'll try my best until Oct 10 11:59PM EDT

**Comment by HeonHeo23** [comment]
@d-e-v-esh 
Thank you for providing good resources!

**Comment by hazardemircan** [comment]
> @hazardemircan I'll try my best until Oct 10 11:59PM EDT

let me know if you need any help 💯

**Comment by d-e-v-esh** [comment]
@HeonHeo23 You don't need to hurry too much, take a couple days and understand the codebase. Currently it's fairly easy to understand. Me and @hazardemircan will help if you need 👍

**Comment by khanjasir90** [comment]
@d-e-v-esh  can i work on this! if @HeonHeo23 is not working.

**Comment by d-e-v-esh** [comment]
@khanjasir90 Yes, sure. I assigned it to you. 👍
