### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by d-e-v-esh** [codeisscience/journal-policy-tracker-backend#75]
Implement the functionality where users can change their password safely.

**Comment by khanjasir90** [comment]
@d-e-v-esh can i work on this!

**Comment by d-e-v-esh** [comment]
@khanjasir90 Sorry but this can't be worked on right now. I'm in the process of putting the app online and automating the processes. Once the things are set up then we can see. Users can't directly change their passwords. They'll get a mail with a link that will guide them to the change password page. You can work on the front end till then👍

**Comment by khanjasir90** [comment]
@d-e-v-esh ! Cool got it. Is there any thing that I can help u with. I would be more than happy to do so.

**Comment by khanjasir90** [comment]
I can help u with setting up the app online as well as automating process etc

**Comment by d-e-v-esh** [comment]
There is nothing much left to do for now until it is online, once it is online, it'll take couple more days I think. I'll let you know 👍

**Comment by d-e-v-esh** [comment]
@khanjasir90 I have changed my mind about this. I think it'll be good if it had a simple change password interface where we need the old password to change it to a new password. You can start working on it and do the implementation. Let me know if you have any problems. 👍

**Comment by khanjasir90** [comment]
@d-e-v-esh sure! will start to work on this.

**Comment by khanjasir90** [comment]
@d-e-v-esh I was working on this issue and just wanted to share that do we really need the old password? According to me just the new password will do the job for us.
My Solution:
Take the new password hash it and check if similar hash exist if yes then old and new passwords are same else update.
Do let me know ur thoughts on this.

**Comment by d-e-v-esh** [comment]
@khanjasir90 Yes you are right, we don't need to old password to update it and put in a new one. But we need the old password so that we can verify that it is the actual owner of the account who is changing the password and not someone else. Therefore we will only change it to the new password if the old password matches.

**Comment by khanjasir90** [comment]
@d-e-v-esh got it! Thanks
