### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by d-e-v-esh** [codeisscience/journal-policy-tracker-backend#76]
The forgot password function will allow users to reset their password and change it to a new one. The user will get an email on their email address which will contain a link. Clicking on that link will take the user to the page where that user can set a new password for their account.

**Comment by hazardemircan** [comment]
You can assign me, my hands got used to the project :)

**Comment by d-e-v-esh** [comment]
I have started working on it already and will make a PR in a couple days. This one will be a little more complex to do as I'll test it with a front-end locally and then push. But thanks you so much for coming forward to help. I really appreciate it. 👍

**Comment by d-e-v-esh** [comment]
Once it's merged, you can work on its implementation on the front-end. 👍

**Comment by hazardemircan** [comment]
> Once it's merged, you can work on its implementation on the front-end. 👍

I can work on that for sure, assign me when it is ready, thanks
