### ISSUE TITLE
Restrict Username Characters

### ISSUE THREAD

**Issue by d-e-v-esh** [codeisscience/journal-policy-tracker-backend#91]
Currently the `username` field for a user can have a string made up of any characters that the user enters. There are no checks for the characters going into `username` field. Therefore, the user can enter any characters in the username field including BLANK_SPACE ( ) and @ which is not good.

The task is to restrict the characters in the `username` field to alphanumeric characters (A–Z, a–z and 0–9, case-sensitive) with the addition of `-` and `_`.

After the implementation of this feature, the user should only be able to enter a string made up of alphanumeric characters, `-` and `_` in the `username` field.

We are already using the [validator](https://www.npmjs.com/package/validator) NPM package in the backend so that can use used to implement this check.

**Comment by khanjasir90** [comment]
@d-e-v-esh can i work on this!

**Comment by d-e-v-esh** [comment]
I assigned it to you 👍

**Comment by khanjasir90** [comment]
@d-e-v-esh username could also contain a period '.'. can we extend it to that too?

**Comment by d-e-v-esh** [comment]
> @d-e-v-esh username could also contain a period '.'. can we extend it to that too?

No, I don't think we need `.`. We can let it go.
