### ISSUE TITLE
Implement string password check

### ISSUE THREAD

**Issue by d-e-v-esh** [codeisscience/journal-policy-tracker-backend#93]
Currently, when we enter a password while registering or changing the password, the app only checks if the entered password contains more than 3 characters. We want to improve upon that and make that password check stronger.

The requirements for a password to be strong are the following:
1. Minimum length -> 8
2. Minimum 1 lowercase character
3. Minimum 1 UPPERCASE character
4. Minimum 1 number character
5. Minimum 1 symbol character

This can be accomplished with the `isStrongPassword` functions in the [validator](https://www.npmjs.com/package/validator) npm package that we are already using.

If the password is not strong return an error in the `password` field defining the requirements for a strong password.

**Comment by khanjasir90** [comment]
@d-e-v-esh can i work on this!

**Comment by Abro0058T** [comment]
Can i work on this ,or is there any other requirement i can work on !?

**Comment by d-e-v-esh** [comment]
@Abro0058T Nasir asked first so I assigned him. You can turn on notification for the repo so you'll know when there is a new issue. You can also look into the front-end repo for issues. 👍

**Comment by Abro0058T** [comment]
Ok sir , one more thing, this is the repo from one of the GSOC project list
right?

**Comment by d-e-v-esh** [comment]
@Abro0058T This was on the list last time. I don't think it'll be on the list next year because it's almost done.

**Comment by d-e-v-esh** [comment]
@Abro0058T This was on the list last time. I don't think it'll be on the list next year because it's almost done.

**Comment by Abro0058T** [comment]
Okk,but i can contribute in this for my proposal (GSOC 2023)? And is there
any other repo you can share  having UI related task in reactjs ? . It will
be help-up

**Comment by d-e-v-esh** [comment]
@Abro0058T You can check the frontend repo in this org. I'm not 100% sure if that'll be in the GSOC either.

**Comment by Abro0058T** [comment]
Ok, thanks.
